### ISSUE TITLE
Cant control via rgb/ww/cw

### ISSUE THREAD

**Issue by Marvo2011** [dmamontov/node-red-contrib-magic-home#1]
Hello,

i have tried to use your plugin.
The on/off and status works fine, but when I will set the color or brightness the lightbulb does nothing. Your status return the new values...

Thanks for your help.

**Comment by dmamontov** [comment]
attach your flow, I will check

**Comment by Marvo2011** [comment]
First pic shows the status request, second the injection for a color change (msg.payload Object...), third the selected device.

![Bildschirmfoto 2020-10-26 um 07 21 20](https://user-images.githubusercontent.com/6094055/97139976-0304ac00-175c-11eb-8453-8a1d0bd00c25.png)
![Bildschirmfoto 2020-10-26 um 07 21 48](https://user-images.githubusercontent.com/6094055/97139998-0c8e1400-175c-11eb-9931-985abea29296.png)
![Bildschirmfoto 2020-10-26 um 07 23 39](https://user-images.githubusercontent.com/6094055/97140141-495a0b00-175c-11eb-91a6-f9fe1a229e9c.png)

**Comment by dmamontov** [comment]
Now I checked it and everything works for me. Do you turn on before color setting?

If possible, send the firmware version and preferably the device model.

**Comment by jangxx** [comment]
@dmamontov You probably have to give the users an option to set the `cold_white_support` option, otherwise the cold white values will not be sent and the controller won't understand the command if they expect it.

**Comment by Marvo2011** [comment]
@dmamontov Yes I turn it on before I tried to set the new color / warme withe values. I will try to reset the light bulbs to get out the firmeware and device model. I think @jangxx have right with the `cold_white_support` option.

**Comment by Marvo2011** [comment]
I have no idea whether it will help but I have maked some TCP dumps.

(Unfortunately I can't get the firmeware and device model because the login prompt on webinterface does not accept the default admin/admin, not even after a device reset :/ ... ) EDIT: I have found the **firmeware version 44.v7** in the app...

Thanks for your help.

First this it whats the Magic Home app is sending on a color (warme white) change:
<img width="1205" alt="Bildschirmfoto 2020-10-29 um 18 50 53" src="https://user-images.githubusercontent.com/6094055/97613851-7ab32f00-1a19-11eb-8181-5121dda5945b.png">

Second this it whats your plugin is sending:
<img width="1197" alt="Bildschirmfoto 2020-10-29 um 18 58 39" src="https://user-images.githubusercontent.com/6094055/97614061-c4037e80-1a19-11eb-9c14-5869ef037981.png">

**Comment by jangxx** [comment]
Ah I see, you have a bulb instead of a LED strip controller. In that case you need to set `apply_masks` to `true` and use `setColor` and `setWarmWhite`/`setWhites` instead of `setColorAndWhites`, since bulbs can not set both at the same time. @dmamontov maybe you could just add a new node for bulbs, since bulbs and controllers behave differently and need different constructor options.

**Comment by Marvo2011** [comment]
@jangxx **Thanks, thats it!** I have changed the `setColorAndWhites` to `setWarmWhite` and added the `apply_masks` option with `true`. And now it is working for the warm white color.

**Comment by dmamontov** [comment]
Merged. Made edits.
