### ISSUE TITLE
Can't add device

### ISSUE THREAD

**Issue by duyuelryel** [dmamontov/node-red-contrib-magic-home#4]
Greetings!
I have just installed your contrib. All of the nodes are installed and can be seen, but i can't add any devices. Is there a specific way to do it please?
Thank you!

**Comment by dmamontov** [comment]
Good day! Devices are scanned automatically if they are in the local network. and are selected in node.

Example settings:
https://ibb.co/QJp77N0

**Comment by duyuelryel** [comment]
![image](https://user-images.githubusercontent.com/11785363/103543996-ad592800-4e9f-11eb-92b3-c546f6f46fa0.png)

Thank you, but it not seems like scanning it. I can see it in my Magic Home app on anroid phone and on my router's DHCP list on local network but not in node-red.
Did i miss something?

**Comment by dmamontov** [comment]
a feeling that there are not enough rights to scan. try pinging your device from the server running node-red.

**Comment by duyuelryel** [comment]
![Képernyőkép erről: 2021-01-04 15-25-01](https://user-images.githubusercontent.com/11785363/103544913-12f9e400-4ea1-11eb-95f2-bc820baaebf1.png)
Seems good.

I have instaled your contrib from node-red palette. Is that enough?

**Comment by dmamontov** [comment]
That should be enough. check if port 5577 is open.

**Comment by duyuelryel** [comment]
![Képernyőkép erről: 2021-01-04 15-32-40](https://user-images.githubusercontent.com/11785363/103545642-2194cb00-4ea2-11eb-9a49-91881f9c6fac.png)
On my led controller, there are no open ports. Strange... My magic home app can control it.

**Comment by dmamontov** [comment]
i am using library: https://www.npmjs.com/package/magic-home

try scanning through it to see if it will give you a list of devices. If it does, check the same thing under the user under which node-red is launched.

**Comment by duyuelryel** [comment]
Thank you. I will try that. I'm not that good in linux yet.

**Comment by duyuelryel** [comment]
![Képernyőkép erről: 2021-01-04 16-20-43](https://user-images.githubusercontent.com/11785363/103550224-e21dad00-4ea8-11eb-84be-2f57a7f79b2f.png)

So. It's strange. for discovery, it say, nothing.
But for query, it shows the current status of the led controller.

**Comment by duyuelryel** [comment]
Hello!
Sadly, i can't make it work with node-red or just simply the magic-home library. 
Discovery not find it, but query can see the status.
Is there a way i can manually add the ip to node-red please? Thank you!

**Comment by dmamontov** [comment]
In theory, I can add if you wait a couple of days.

**Comment by duyuelryel** [comment]
I can't make it work an i can't see it withouth node-red , so i have time. Maybe it will help for others too later! Thank you for your help and time!

**Comment by RalphLemarechal** [comment]
Hi !

I have the exact same issue, can control the led through the android app, it's discoverable (see below), and also works with node-red-contrib-magichome (but I want the pattern option).

Being able to set the ip address manually would be a great workaround :-)

**Comment by duyuelryel** [comment]
I did try this: https://flows.nodered.org/node/node-red-contrib-magichome-controller
and it seems, i can controll the LED strip with it manually. So the only problem is the discovery.

**Comment by RalphLemarechal** [comment]
Those nodes also don't work with me.... same behaviour. Must be a networking issue but still, hardcoding the ip would do.

**Comment by dmamontov** [comment]
Updated version, added more device settings. and also manually register ip.

https://www.npmjs.com/package/node-red-contrib-magic-home-local

**Comment by hasspi88** [comment]
Hello, I installed your node, but I don't know how to use it, such as switch, palette, homekit. Is there an example stream
