### ISSUE TITLE
I can only turn the light on, not off

### ISSUE THREAD

**Issue by hasspi88** [dmamontov/node-red-contrib-magic-home#6]
![009](https://user-images.githubusercontent.com/77336160/105122089-84c46580-5b10-11eb-9ac8-a05931646228.png)

**Comment by hasspi88** [comment]
https://discord.gg/PVwEG6Sd

**Comment by homefefeld** [comment]
same here, can only turn on the led, can not turn it off.

**Comment by igi79** [comment]
Example payloads for nodes:
**status**
- `msg.payload = true`

**on/off**
- turn on: `msg.payload = true` (boolean)
- turn off:`msg.payload = false` (boolean)

**rgb**
- set to red: `msg.payload = {"r": 255, "g": 0, "b": 0}` (json)
- set to dim white: `msg.payload = {"r": 100, "g": 100, "b": 100}` (json)

**cw**
- set to warm white (if your LED strip has some): `msg.payload = {"ww": 255, "cw": 0}` (json)
- set to cold white (if your LED strip has some): `msg.payload = {"ww": 0, "cw": 255}` (json)

**pattern**
- turn on predefined: `msg.payload = true` (boolean)
- custom: `msg.payload = {"type": "fade|jump|strobe", "speed": 100, "custom": [ [r1, g1, b1], [r2, g2, b2], ...]}` (json)

If your LED waits 10s for next command, set its timeout to 1 (default is 10000 = 10s). My Aliexpress LED strip correctly responds only for status and on/off, but all commands work just fine.

**Comment by homefefeld** [comment]
managed to get it working...
for some reason I needed to apply "homemagic the status" after the "on-off"....
so I did the following and it is now working fine 👍 
![image](https://user-images.githubusercontent.com/3512839/105592747-fe6b8600-5d92-11eb-914d-84ffa1ce398e.png)
thanks for this node !!!!
all the best.

**Comment by igi79** [comment]
LED responds with OK only for status and on/off node:
![image](https://user-images.githubusercontent.com/9699253/105614873-920d7880-5dcc-11eb-9431-65f5426c30c9.png)
even though, all nodes do what they should...
@dmamontov - would be great to have response optional only.... (?)

**Comment by hasspi88** [comment]
> LED仅对状态和打开/关闭节点做出OK响应： 尽管，所有节点都按其应做的方式进行操作... @dmamontov-将响应仅作为可选参数很好....（？）
> ![图片](https://user-images.githubusercontent.com/9699253/105614873-920d7880-5dcc-11eb-9431-65f5426c30c9.png)

![image](https://user-images.githubusercontent.com/77336160/105928284-a1b4e780-6080-11eb-8344-a239566ef7d1.png)

**Comment by hasspi88** [comment]
![image](https://user-images.githubusercontent.com/77336160/105928345-bf824c80-6080-11eb-9f42-c628cc174c74.png)

**Comment by hasspi88** [comment]
节点 的方式不正确，你应该像我这样使用节点，但是我不知道怎么正确的写他的函数去控制cw，你可以导出代码示例吗？
@igi79

**Comment by hasspi88** [comment]
@我猜测他现在是关灯状态所以它是error

**Comment by hasspi88** [comment]
@dmamontov 你可以来这里，有两个都是开发magichome插件的工程师，https://discord.gg/q4M5eAg7
